name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  linux-windows-build:
    name: CSharp Build
    runs-on: windows-latest
    timeout-minutes: 45
    steps:

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
  
    - name: Check out code
      uses: actions/checkout@v2

    - name: Git Fetch Tags
      run: git fetch --prune --unshallow --tags -f
      
    - name: Create Git Tag
      id: tag
      run: |
        $TAG_NAME = (Get-Date).ToString('yyyyMMddHHmmss')
        echo "TAG_NAME=$TAG_NAME" >> $env:GITHUB_ENV
        
    - name: MSBuild
      run: |
        msbuild.exe Watson.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=compiled/
        dir Seatbelt/compiled

    - name: Upload Release Package
      uses: softprops/action-gh-release@v2
      with:
        files: Seatbelt/compiled/*
        tag_name: ${{ env.TAG_NAME }}
